---
# tasks file for headnode

- name: install headnode only packages
  apt: pkg={{item}} state=present
  with_items:
  - tmux
  - automake
  - dnsmasq
  - iptables-persistent
  - netfilter-persistent

- name: setup interfaces
  copy: src=interfaces dest=/etc/network/interfaces
  notify:
   - restart interfaces

- name: Ensure net.ipv4.ip_forward is set to 1 in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    create: yes

- name: Apply sysctl settings
  command: sysctl -p

- name: add IP forwarding
  command: iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

- name: Save netfilter config
  command: netfilter-persistent save

- name: Reload netfilter config
  command: netfilter-persistent reload

- name: setup DNSmasq
  copy: src=dnsmasq.conf dest=/etc/
  notify:
   - restart dnsmasq
